ITEM.name = "Bren L4A3"
ITEM.description = "The Bren, with its iconic top-loading magazine design, has been in use by many European and Asian countries since World War 2. This variant was converted to 7.62x51 in the 50s, and ones like it were in use across multiple variants well into the 90s."
ITEM.model = "models/khrcw2/doipack/w_bren.mdl"
ITEM.class = "doi_atow_bren"
ITEM.weaponCategory = "primary"
ITEM.width = 5
ITEM.height = 2
ITEM.price = 60000
ITEM.flag = "A"
ITEM.isWeapon = true
ITEM.isPLWeapon = true
ITEM.isCW = true
ITEM.modifier = 5
ITEM.weight = 11.5
ITEM.repairCost = ITEM.price/100*1
ITEM.Range = 150
ITEM.Pen = 18
ITEM.Mag = 20
ITEM.barrel = "medium"
ITEM.weaponType = "heavyweapons"
ITEM.RPM = 5
ITEM.recoil = -5