ITEM.name = "DP28"
ITEM.description = "The Degtyaryov machine gun or DP-27 is a light machine gun firing the 7.62x54mmR cartridge that was primarily used by the Soviet Union. Besides being the standard Soviet infantry light machine gun during World War II, with various modifications it was used in aircraft as a flexible defensive wepaon, and itequipped almost all Soviet tanks in WWII as either a flexible bow machine gun or a co-axial machine gun controlled by the gunner. Uses 7.62x54mmR.\n\n-This Weapon is Heavy, meaning it adds +1 Weight when Equipped.\n\nShots per round: 6"
ITEM.model = "models/weapons/w_ro2_dp28.mdl"
ITEM.class = "cw_sil_dp28"
ITEM.weaponCategory = "primary "
ITEM.width = 5
ITEM.height = 2
ITEM.price = 65000
ITEM.flag = "A"
ITEM.isWeapon = true
ITEM.isPLWeapon = true
ITEM.isCW = true
ITEM.modifier = 20
ITEM.weight = 11.5
ITEM.repairCost = ITEM.price/100*1
ITEM.Range = 150
ITEM.Pen = 18
ITEM.Mag = 47
ITEM.barrel = "medium"
ITEM.weaponType = "heavyweapons"
ITEM.RPM = 5
ITEM.recoil = -5
ITEM.bipodIncluded = true