ITEM.name = "GSh-18"
ITEM.description= "A Russian handgun that fires 9x19mm."
ITEM.longdesc = "The GSh-18 is a 9 mm semi-automatic pistol developed by the KBP Instrument Design Bureau in Tula during the 1990s. The pistol's name is derived from its designers (Gryazev and Shipunov) and its magazine capacity of 18 rounds.\n\nAmmo: 9x19mm\nMagazine Capacity: 18\n\n-This weapon is a Secondary, meaning it may be used even when Stunned.\n\n-This weapon is designated as Light, meaning it can be reloaded using 4s of Movement speed instead of a full action.\n\n-Shots per round: 4"
ITEM.model = "models/weapons/gsh18/w_gsh18.mdl"
ITEM.class = "cw_sil_gsh18"
ITEM.weaponCategory = "sidearm"
ITEM.width = 2
ITEM.price = 3250
ITEM.height = 1
ITEM.flag = "3"
ITEM.Range = 30
ITEM.Pen = 5
ITEM.Mag = 18
ITEM.isCW = true
ITEM.isPLWeapon = true
ITEM.modifier = 5
ITEM.weight = 0.590
ITEM.barrel = "short"