ITEM.name = "MP-443 Grach"
ITEM.description = "The MP-443 Grach, following traditional Russian naming procedure, is the Russian standard military-issue side arm. It fires 9x19 rounds.\n\n-This weapon is a Secondary, meaning it may be used even when Stunned.\n\n-This weapon is designated as Light, meaning it can be reloaded using 4s of Movement speed instead of a full action.\n\n-Shots per round: 4"
ITEM.model = "models/weapons/ethereal/w_grach.mdl"
ITEM.class = "cw_sil_grach"
ITEM.weaponCategory = "sidearm"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 2600
ITEM.flag = "3"
ITEM.isWeapon = true
ITEM.isPLWeapon = true
ITEM.isCW = true
ITEM.modifier = 11
ITEM.weight = 0.95
ITEM.repairCost = ITEM.price/100*1
ITEM.Range = 30
ITEM.Pen = 5
ITEM.Mag = 18
ITEM.barrel = "short"