ITEM.name = "MP-412 REX"
ITEM.description = "he MP-412 REX was a Russian double-action/single-action revolver designed by the state-owned Izhevsk Mechanical Plant, with a break-action chamber and an automatic ejector, chambered for the .357 Magnum round.\n\n-This weapon is a Secondary, meaning it may be used even when Stunned.\n\n-This weapon can be designated as Light with Speed-Loaders, meaning it could be reloaded using 4s of Movement speed instead of a full action.\n\n-Shots per round: 2"
ITEM.model = "models/silver/stalker/weapons/w_mp412.mdl"
ITEM.class = "cw_sil_mp412"
ITEM.weaponCategory = "sidearm"
ITEM.width = 2
ITEM.height = 1
ITEM.price = 20000
ITEM.flag = "4" 
ITEM.isWeapon = true
ITEM.isPLWeapon = true
ITEM.isCW = true
ITEM.modifier = 2
ITEM.weight = 0.90
ITEM.Range = 30
ITEM.Pen = 4
ITEM.Mag = 6
ITEM.barrel = "medium"