ITEM.name = "P226R"
ITEM.description = "The SIG Sauer P226 is a full-sized, service-type pistol made by SIG Sauer. It is chambered for the 9×19mm Parabellum, .40 S&W, .357 SIG, and .22 Long Rifle. It is essentially the same basic design of the SIG Sauer P220, but developed to use higher capacity, double stack magazines in place of the single stack magazines of the P220. These particular variants fire the 9x19mm Round.\n\n-This weapon is a Secondary, meaning it may be used even when Stunned.\n\n-This weapon is designated as Light, meaning it can be reloaded using 4s of Movement speed instead of a full action.\n\n-Shots per round: 4"
ITEM.model = "models/silver/stalker/weapons/w_p226.mdl"
ITEM.class = "cw_sil_p226"
ITEM.weaponCategory = "sidearm"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 1800
ITEM.flag = "3"
ITEM.isWeapon = true
ITEM.isPLWeapon = true 
ITEM.isCW = true
ITEM.modifier = 13
ITEM.weight = 0.964
ITEM.Range = 30
ITEM.Pen = 5
ITEM.Mag = 15
ITEM.barrel = "short"