ITEM.name = "Serbu Super Shorty"
ITEM.description = "A very curious CQC specimen."
ITEM.longdesc = "The Serbu Super Shorty is a unique creation from Serbu Firearms, a company that otherwise only makes affordable .50 BMG rifles. It's effectively a sawnoff shotgun that's more controllable thanks to a folding grip, and can chamber a shell to allow a total of three shots before reloading. Popular with Bandits who've got a bit of cash and want to up their trenchcoat-gun game."
ITEM.model = "models/weapons/w_shot_shortygun.mdl"
ITEM.class = "cw_m3supershort"
ITEM.weaponCategory = "secondary"
ITEM.width = 3
ITEM.height = 1
ITEM.price = 15000
ITEM.isWeapon = true
ITEM.isPLWeapon = true
ITEM.isCW = true
ITEM.modifier = 20
ITEM.weight = 3.7
ITEM.flag = "3"
ITEM.Range = 50
ITEM.Pen = 5
ITEM.Mag = 5
ITEM.barrel = "medium"
ITEM.weaponType = "closequarters"
ITEM.RPM = 2
ITEM.recoil = -4