ITEM.name = "USP .45"
ITEM.description = "The USP is a semi-automatic pistol developed in Germany by Heckler & Koch GmbH (H&K) of Oberndorf am Neckar as a replacement for the P7 series of handguns. This particular variant is chambered for the .45 ACP Round.\n\n-This weapon is a Secondary, meaning it may be used even when Stunned.\n\n-This weapon is designated as Light, meaning it can be reloaded using 4s of Movement speed instead of a full action.\n\n-Shots per round: 4"
ITEM.model = "models/silver/stalker/weapons/w_usp45.mdl"
ITEM.class = "cw_sil_usp45"
ITEM.weaponCategory = "sidearm"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 4600
ITEM.flag = "3"
ITEM.isWeapon = true
ITEM.isPLWeapon = true
ITEM.isCW = true
ITEM.modifier = 13
ITEM.weight = 0.789
ITEM.Range = 50
ITEM.Pen = 4
ITEM.Mag = 12
ITEM.barrel = "short"