ITEM.name = "Berkut Riot Armor (Female)"
ITEM.model = "models/kek1ch/merc_outfit.mdl"
ITEM.replacements = "models/nasca/stalker/female_expedition.mdl"
ITEM.description= "A suit of riot gear."
ITEM.longdesc = "This uniform is commonly used by police outside of the Zone who use it to control mobs of unruly civilians. As such it is thick, unwieldy and generally possesses poor environmental protection. However, it makes up for this shortcoming with decent ballistic protection, and padding against blunt and bladed strikes, making it a popular choice for mutant hunting."
ITEM.width = 2
ITEM.height = 2
ITEM.price = 2000
ITEM.flag = "3"
ITEM.br = 0.3
ITEM.fbr = 1
ITEM.ar = 0.2
ITEM.far = 1
ITEM.isArmor = true
ITEM.overlayPath = "vgui/overlays/hud_gas"
ITEM.img = Material("vgui/hud/eo20.png")
ITEM.artifactcontainers = {"1"}
ITEM.weight = 10
ITEM.weightClass = 2
ITEM.ballisticRating = 25
ITEM.res = {
	["Impact"] = 0.20,
	["Rupture"] = 0.30,
	["Bullet"] = 0.12,
	["Shock"] = 0.02,
	["Burn"] = 0.10,
	["Radiation"] = 0,
	["Chemical"] = 0,
	["Psi"] = 0,
}

ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}