ITEM.name = "Berkut Riot Armor (Female)"
ITEM.model = "models/kek1ch/merc_outfit.mdl"
ITEM.replacements = "models/nasca/stalker/female_expedition.mdl"
ITEM.description= "A suit of riot gear."
ITEM.longdesc = "This uniform is commonly used by police outside of the Zone who use it to control mobs of unruly civilians. As such it is thick, unwieldy and generally possesses poor environmental protection. However, it makes up for this shortcoming with excellent ballistic protection, making it common among stalkers who expect to bear the worst combat has to offer.\n\nBallistic Protection:\nTorso: IIIA\nLimbs: IIIA\nWeight: 3"
ITEM.width = 2
ITEM.height = 2
ITEM.price = 40000
ITEM.flag = "3"
ITEM.br = 0.3
ITEM.fbr = 1
ITEM.ar = 0.2
ITEM.far = 1
ITEM.isGasmask = true
ITEM.isHelmet = true
ITEM.isArmor = true
ITEM.overlayPath = "vgui/overlays/hud_gas"
ITEM.img = Material("vgui/hud/eo20.png")
ITEM.artifactcontainers = {"1"}
ITEM.weight = 10
ITEM.maxArmor = 20
ITEM.res = {
	["Bullet"] = 0.5,
	["Blast"] = 0.5,
	["Fall"] = 0.5,
	["Burn"] = 0.1,
	["Radiation"] = 0.2,
	["Chemical"] = 0.2,
	["Shock"] = 0.0,
	["Psi"] = 0.0,
}

ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}