ITEM.name = "Beryl-1 Service Uniform" 
ITEM.model = "models/kek1ch/spec_sold_outfit.mdl"
ITEM.replacements = "models/nasca/stalker/male_berill1.mdl"
ITEM.description= "A Berill-1 uniform." 
ITEM.longdesc = "A poor protective outfit contracted by government officials to the lowest bidder. It's been largely phased out in favor of a more cost-effective improvement, but is still issued to pilots, medics, or techs that don't leave the base... or VERY unlucky conscripts."
ITEM.width = 2
ITEM.height = 1
ITEM.price = 8000
ITEM.flag = "1"
ITEM.br = 0.2
ITEM.fbr = 1
ITEM.ar = 0.1
ITEM.far = 1
ITEM.isArmor = true
ITEM.artifactcontainers = {"1"} 
ITEM.img = Material("vgui/hud/berill7.png")
ITEM.weight = 7
ITEM.weightClass = 1
ITEM.ballisticRating = 19
ITEM.res = {
	["Impact"] = 0.01,
	["Rupture"] = 0.19,
	["Bullet"] = 0.07,
	["Shock"] = 0.03,
	["Burn"] = 0.04,
	["Radiation"] = 0,
	["Chemical"] = 0.03,
	["Psi"] = 0,
}

ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}