ITEM.name = "\"Black\" Hawk"
ITEM.model ="models/kek1ch/merc_outfit.mdl"
ITEM.replacements = "models/nasca/stalker/male_hawk_bandit.mdl"
ITEM.description= "A bandit twist on the standard mercenary suit."
ITEM.longdesc = "A bandit variant of the Hawk suit, the suit has seen considerable modification to fit the needs of camp raiders and thugs.   .\n\nBallistic Protection:\nSkull: II\nNeck & Face: 0\nTorso: IIIA\nLimbs: II\nWeight: 1"
ITEM.width = 2
ITEM.height = 1
ITEM.price = 14000
ITEM.flag = "A"
ITEM.br = 0.2
ITEM.fbr = 8
ITEM.ar = 0.05
ITEM.far = 1.5
ITEM.isGasmask = true
ITEM.isHelmet = true
ITEM.isArmor = true
ITEM.overlayPath = "vgui/overlays/hud_merc"
ITEM.img = Material("vgui/hud/xm40.png")
ITEM.artifactcontainers = {"0"}
ITEM.weight = 5
ITEM.maxArmor = 10
ITEM.res = {
	["Bullet"] = 0.4,
	["Blast"] = 0.4,
	["Fall"] = 0.4,
	["Burn"] = 0,
	["Radiation"] = 0.1,
	["Chemical"] = 0.1,
	["Shock"] = 0,
	["Psi"] = 0,
}

ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}