ITEM.name = "\"Black\" Hawk"
ITEM.model ="models/kek1ch/merc_outfit.mdl"
ITEM.replacements = "models/nasca/stalker/male_hawk_bandit.mdl"
ITEM.description= "A bandit twist on the standard mercenary suit."
ITEM.longdesc = "A bandit variant of the Hawk suit, the suit has seen considerable modification to fit the needs of camp raiders and thugs."
ITEM.width = 2
ITEM.height = 1
ITEM.price = 14000
ITEM.flag = "A"
ITEM.br = 0.2
ITEM.fbr = 8
ITEM.ar = 0.05
ITEM.far = 1.5
ITEM.isArmor = true
ITEM.overlayPath = "vgui/overlays/hud_merc"
ITEM.img = Material("vgui/hud/xm40.png")
ITEM.artifactcontainers = {"1"}
ITEM.weightClass = 1
ITEM.ballisticRating = 27
ITEM.res = {
	["Impact"] = 0.06,
	["Rupture"] = 0.08,
	["Bullet"] = 0.12,
	["Shock"] = 0.03,
	["Burn"] = 0.02,
	["Radiation"] = 0.02,
	["Chemical"] = 0.02,
	["Psi"] = 0,
}
ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}