ITEM.name = "Beryl-3 Improved Infantry Armor" 
ITEM.model = "models/kek1ch/spec_sold_outfit.mdl"
ITEM.replacements = "models/nasca/stalker/male_berill1.mdl"
ITEM.description= "A retrofitted Military service uniform." 
ITEM.longdesc = "The Beryl-3M is a recent creation by the Military in an attempt to use newfound resources to shore up the effectiveness of their standard infantry, utilizing a steel helmet and improved kevlar. It is issued to soldiers along the border or in areas under firm Military control, for the odd skirmish with lightly armed Rookies or mutants that wander too close for comfort."
ITEM.width = 2
ITEM.height = 2
ITEM.price = 32000
ITEM.flag = "A"
ITEM.br = 0.2
ITEM.fbr = 1
ITEM.ar = 0.1
ITEM.far = 1
ITEM.isArmor = true
ITEM.artifactcontainers = {"1"} 
ITEM.img = Material("vgui/hud/berill7.png")
ITEM.weightClass = 2
ITEM.ballisticRating = 32
ITEM.res = {
	["Impact"] = 0.15,
	["Rupture"] = 0.30,
	["Bullet"] = 0.15,
	["Shock"] = 0.05,
	["Burn"] = 0.13,
	["Radiation"] = 0.05,
	["Chemical"] = 0.03,
	["Psi"] = 0.05,
}

ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}