ITEM.name = "CS-2 Patrol Armor"
ITEM.model ="models/kek1ch/cs_heavy_outfit.mdl"
ITEM.replacements ="models/nasca/stalker/male_cs2.mdl"
ITEM.description= "A Clear Sky patrol suit."
ITEM.longdesc = "A waterproof bodysuit intended for protecting and surveying areas scouted by Clear Sky. It implements Clear Sky's AIR-1 protective solution as a safeguard against environmental hazards, while its lightweight bulletproof vest is capable of stopping low-caliber rounds"
ITEM.width = 2
ITEM.height = 2
ITEM.price = 35000
ITEM.flag = "3"
ITEM.br = 0.28
ITEM.fbr = 8
ITEM.ar = 0.20
ITEM.far = 3
ITEM.isArmor = true
ITEM.overlayPath = "vgui/overlays/hud_gas"
ITEM.img = Material("vgui/hud/eo20.png")
ITEM.artifactcontainers = {"2"}
ITEM.weightClass = 2
ITEM.ballisticRating = 23
ITEM.res = {
	["Impact"] = 0.13,
	["Rupture"] = 0.12,
	["Bullet"] = 0.09,
	["Shock"] = 0.09,
	["Burn"] = 0.31,
	["Radiation"] = 0.07,
	["Chemical"] = 0.09,
	["Psi"] = 0,
}

ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}