ITEM.name = "CS-3b Heavy Assault Armor"
ITEM.model = "models/kek1ch/cs_heavy_outfit.mdl"
ITEM.replacements = "models/nasca/stalker/male_cs3b.mdl"
ITEM.description = "A Clear Sky assault suit."
ITEM.longdesc = "Featuring a thick combat vest layered over a baggy canvas bodysuit infused with the experimental AIR-2 solution, this suit was the final proprietary design ever created by Clear Sky. Invented in preparation for the battle in Limansk, after Clear Sky's destruction this suit serves only as a reminder that even excellent protective armor cannot guarantee safety on the wrong side of the perimeter.\n\nBallistic Protection:\nTorso: IV\nLimbs: IIIA\nWeight: 3"
ITEM.width = 2
ITEM.height = 3
ITEM.price = 200000
ITEM.flag = "A"
ITEM.br = 0.5
ITEM.fbr = 5
ITEM.ar = 0.4
ITEM.far = 4
ITEM.isArmor = true
ITEM.overlayPath = "vgui/overlays/hud_gas"
ITEM.img = Material("vgui/hud/eo20.png")
ITEM.artifactcontainers = {"3"}
ITEM.noBusiness = true
ITEM.weightClass = 3
ITEM.ballisticRating = 45
ITEM.res = {
	["Impact"] = 0.24,
	["Rupture"] = 0.23,
	["Bullet"] = 0.24,
	["Shock"] = 0.13,
	["Burn"] = 0.16,
	["Radiation"] = 0.10,
	["Chemical"] = 0.03,
	["Psi"] = 0.04,
}

ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}