ITEM.name = "\"Dusk\" Stalker Suit" 
ITEM.model = "models/kek1ch/stalker_outfit.mdl"
ITEM.replacements = "models/nasca/stalker/male_dusk_lone.mdl"
ITEM.description = "An armored stalker suit." 
ITEM.longdesc = "An overall upgrade over the Sunrise suit, the Dusk features enhanced protection in a firefight while also being surprisingly comfortable to wear. For this reason, it can be a favored choice among any stalker who needs a little more protection than what the average stalker suit can afford."
ITEM.width = 2
ITEM.height = 2
ITEM.price = 17000
ITEM.flag = "3"
ITEM.br = 0.2
ITEM.fbr = 7
ITEM.ar = 0.2
ITEM.far = 3
ITEM.isArmor = true
ITEM.img = Material("vgui/hud/ps5m.png")
ITEM.overlayPath = "vgui/overlays/hud_gas"
ITEM.img = Material("vgui/hud/eo20.png")
ITEM.artifactcontainers = {"2"}
ITEM.weight = 10
ITEM.maxArmor = 10
ITEM.weightClass = 2
ITEM.ballisticRating = 30
ITEM.res = {
	["Impact"] = 0.15,
	["Rupture"] = 0.27,
	["Bullet"] = 0.11,
	["Shock"] = 0.07,
	["Burn"] = 0.13,
	["Radiation"] = 0.08,
	["Chemical"] = 0.03,
	["Psi"] = 0.07,
}

ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}