ITEM.name = "TB-3 Exoskeleton"
ITEM.model = "models/kek1ch/exolight_outfit.mdl"
ITEM.replacements = "models/nasca/stalker/male_exo_lone.mdl"
ITEM.description = "A set of TB-3 heavy armor on a third-gen exoskeleton."
ITEM.longdesc = "A complete set of exosuit and exoskeleton, this suit consists of a heavy armored vest and a reinforced environmental jumpsuit. While mistakenly referred to as a radiation suit, this outfit actually eschews most environmental protection in favor of raw combat potential. It is used by many veteran stalkers in the most dangerous parts of the Zone. The Exoskeleton inhibits movement, but allows for feats of strength and carrying even more armor on the base suit."
ITEM.width = 3
ITEM.height = 3
ITEM.price = 250000
ITEM.flag = "A"
ITEM.br = 0.6
ITEM.fbr = 11
ITEM.ar = 0.2
ITEM.far = 3
ITEM.isGasmask = true
ITEM.isHelmet = false
ITEM.isArmor = true
ITEM.overlayPath = "vgui/overlays/hud_merc"
ITEM.img = Material("vgui/hud/xm40.png")
ITEM.artifactcontainers = {"3"}
ITEM.noBusiness = true
ITEM.weight = 26
ITEM.weightClass = 5
ITEM.ballisticRating = 59
ITEM.res = {
	["Impact"] = 0.28,
	["Rupture"] = 0.34,
	["Bullet"] = 0.33,
	["Shock"] = 0.07,
	["Burn"] = 0.08,
	["Radiation"] = 0.10,
	["Chemical"] = 0.05,
	["Psi"] = 0.10,
}
ITEM.newSkin = 0
ITEM.bodyGroups = {
	["Servomotors"] = 1,
}