ITEM.name = "UNISG LC-UC Suit"
ITEM.model = "models/kek1ch/merc_outfit.mdl"
ITEM.replacements = "models/player/stalker_isg/isg_gear/isg_gear.mdl"
ITEM.description= "A Mercenary suit modified by the ISG."
ITEM.longdesc = "One of the first suits commissioned for the UNISG, in their earliest days - effectively the same base suit used by the Mercenaries with some improved materials. Among newer Stalkers it would serve as a very well rounded suit, but nowadays is only issued to scouts as it doesn't fully serve the needs of the gorup today."
ITEM.width = 2
ITEM.height = 1
ITEM.price = 14000
ITEM.flag = "A"
ITEM.br = 0.2
ITEM.fbr = 8
ITEM.ar = 0.05
ITEM.far = 1.5
ITEM.isArmor = true
ITEM.overlayPath = "vgui/overlays/hud_merc"
ITEM.img = Material("vgui/hud/xm40.png")
ITEM.artifactcontainers = {"1"}
ITEM.weightClass = 1
ITEM.ballisticRating = 27
ITEM.res = {
	["Impact"] = 0.15,
	["Rupture"] = 0.18,
	["Bullet"] = 0.12,
	["Shock"] = 0.05,
	["Burn"] = 0.12,
	["Radiation"] = 0.07,
	["Chemical"] = 0.05,
	["Psi"] = 0,
}
ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}