ITEM.name = "UNISG Mk II Tactical Armor" 
ITEM.model = "models/kek1ch/stalker_outfit.mdl"
ITEM.replacements = "models/player/stalker_isg/isg_sunrise/isg_sunrise.mdl"
ITEM.description= "A tactical body armor made for the ISG."
ITEM.longdesc = "The current standard issue for ISG tactical teams, offering balanced anomaly and combat protection to its users."
ITEM.width = 2
ITEM.height = 2
ITEM.price = 25000
ITEM.flag = "A"
ITEM.br = 0.2
ITEM.fbr = 7
ITEM.ar = 0.2
ITEM.far = 3
ITEM.isArmor = true
ITEM.overlayPath = "vgui/overlays/hud_gas"
ITEM.img = Material("vgui/hud/eo20.png")
ITEM.artifactcontainers = {"2"}
ITEM.weightClass = 2
ITEM.ballisticRating = 26
ITEM.res = {
	["Impact"] = 0.15,
	["Rupture"] = 0.18,
	["Bullet"] = 0.24,
	["Shock"] = 0.18,
	["Burn"] = 0.35,
	["Radiation"] = 0.11,
	["Chemical"] = 0.15,
	["Psi"] = 0,
}

ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}