ITEM.name = "UNISG IBAz Assault Suit"
ITEM.model = "models/kek1ch/exolight_outfit.mdl"
ITEM.replacements = "models/player/stalker_isg/isg_metro/isg_metro.mdl"
ITEM.description = "A suit of ISG lab-raiding gear."
ITEM.longdesc = "A set of heavier armor assembled by UN armorsmiths, creating a hefty assault suit created for raiding classified sites and handling the many threats inside."
ITEM.width = 2
ITEM.height = 4
ITEM.price = 125000
ITEM.flag = "A"
ITEM.br = 0.6
ITEM.fbr = 11
ITEM.ar = 0.2
ITEM.far = 3
ITEM.isArmor = true
ITEM.overlayPath = "vgui/overlays/hud_merc"
ITEM.img = Material("vgui/hud/xm40.png")
ITEM.artifactcontainers = {"1"}
ITEM.noBusiness = true
ITEM.weightClass = 2
ITEM.ballisticRating = 42
ITEM.res = {
	["Impact"] = 0.18,
	["Rupture"] = 0.23,
	["Bullet"] = 0.26,
	["Shock"] = 0.28,
	["Burn"] = 0.15,
	["Radiation"] = 0.10,
	["Chemical"] = 0.05,
	["Psi"] = 0.09,
}

