ITEM.name = "\"Jupiter\" Suit" 
ITEM.model = "models/kek1ch/spec_sold_outfit.mdl"
ITEM.replacements = "models/nasca/stalker/male_jupiter_eco.mdl"
ITEM.description = "A mix of a SEVA and an old PSZ-12 suit." 
ITEM.longdesc = "A zone-made amalgamam of an old PSZ-12 assault suit and a SEVA Anomaly Suppression Device, with some environmental layers replacing parts of armor. It's somewhat ramshackle, but is used mostly by Loners wanting to be decently equipped in any scenario."
ITEM.width = 2
ITEM.height = 2
ITEM.price = 150000
ITEM.flag = "3"
ITEM.br = 0.2
ITEM.fbr = 7
ITEM.ar = 0.2
ITEM.far = 3
ITEM.isArmor = true
ITEM.img = Material("vgui/hud/ps5m.png")
ITEM.overlayPath = "vgui/overlays/hud_gas"
ITEM.img = Material("vgui/hud/eo20.png")
ITEM.artifactcontainers = {"3"}
ITEM.weight = 10
ITEM.maxArmor = 10
ITEM.weightClass = 3
ITEM.ballisticRating = 40
ITEM.res = {
	["Impact"] = 0.25,
	["Rupture"] = 0.33,
	["Bullet"] = 0.25,
	["Shock"] = 0.17,
	["Burn"] = 0.50,
	["Radiation"] = 0.15,
	["Chemical"] = 0.05,
	["Psi"] = 0.10,
}

ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}