ITEM.name = "SRS-W \"Wolven\" (Female) "
ITEM.model = "models/kek1ch/stalker_outfit.mdl"
ITEM.replacements = "models/silver/stalker/female_sunrise_merc.mdl"
ITEM.description= "A modified PSZ-9 suit used by Mercenaries." 
ITEM.longdesc = "This PSZ-9 is a creation for Blue Eagle with secrets either stolen or shared from Freedom, knowing their on-off relationship. It is intended for mercs whose tasks will see a fair amount of both anomaly interaction and light combat."
ITEM.width = 2
ITEM.height = 2
ITEM.price = 40000
ITEM.flag = "3"
ITEM.br = 0.2
ITEM.fbr = 7
ITEM.ar = 0.2
ITEM.far = 3
ITEM.isGasmask = true
ITEM.isHelmet = true
ITEM.isArmor = true
ITEM.overlayPath = "vgui/overlays/hud_gas"
ITEM.img = Material("vgui/hud/eo20.png")
ITEM.noBusiness = true
ITEM.artifactcontainers = {"2"}
ITEM.weight = 13
ITEM.weightClass = 2
ITEM.ballisticRating = 32
ITEM.res = {
	["Impact"] = 0.08,
	["Rupture"] = 0.13,
	["Bullet"] = 0.11,
	["Shock"] = 0.05,
	["Burn"] = 0.35,
	["Radiation"] = 0.03,
	["Chemical"] = 0.04,
	["Psi"] = 0,
}

ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}