ITEM.name = "Monolith Suit"
ITEM.model = "models/kek1ch/monolith_outfit.mdl"
ITEM.replacements = "models/nasca/stalker/male_sunrise_mono.mdl"
ITEM.description = "A suit worn by the Monolith."
ITEM.longdesc = "A mysterious outfit worn as standard by members of the Monolith faction. This advanced design consists of an environmental bodysuit that provides more than radiological protection, underneath a bulletproof vest. With these suits being discovered in underground labs, this suit is considered taboo among stalkers."
ITEM.width = 2
ITEM.height = 2
ITEM.price = 45000
ITEM.flag = "1"
ITEM.br = 0.15
ITEM.fbr = 6
ITEM.ar = 0.15
ITEM.far = 2
ITEM.isArmor = true
ITEM.repairCost = ITEM.price/100*1
ITEM.overlayPath = "vgui/overlays/hud_gas"
ITEM.img = Material("vgui/hud/eo20.png")
ITEM.noBusiness = true
ITEM.artifactcontainers = {"2"}
ITEM.weightClass = 2
ITEM.ballisticRating = 36
ITEM.res = {
	["Impact"] = 0.05,
	["Rupture"] = 0.13,
	["Bullet"] = 0.11,
	["Shock"] = 0.05,
	["Burn"] = 0.35,
	["Radiation"] = 0.03,
	["Chemical"] = 0.04,
	["Psi"] = 0,
}

ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}