ITEM.name = "STS-N \"Nighthunter\" "
ITEM.model ="models/kek1ch/merc_outfit.mdl"
ITEM.replacements = "models/nasca/stalker/male_eagle_merc.mdl"
ITEM.description= "An elite mercenary suit."
ITEM.longdesc = "A tactical uniform issued to elite Mercenary squads operating in combat areas in the Zone's northern reaches, this outfit boasts better physical protection on top of an even better weight distribution system than its predecessor. Naturally, its price is higher than that of its lighter cousins, but is a valued presence in battle all the same."
ITEM.width = 2
ITEM.height = 2
ITEM.price = 80000
ITEM.flag = "A"
ITEM.br = 0.3
ITEM.fbr = 1
ITEM.ar = 0.1
ITEM.far = 0
ITEM.isArmor = true
ITEM.overlayPath = "vgui/overlays/hud_merc"
ITEM.img = Material("vgui/hud/xm40.png")
ITEM.artifactcontainers = {"1"}
ITEM.weightClass = 2
ITEM.ballisticRating = 38
ITEM.res = {
	["Impact"] = 0.18,
	["Rupture"] = 0.18,
	["Bullet"] = 0.24,
	["Shock"] = 0.05,
	["Burn"] = 0.12,
	["Radiation"] = 0.10,
	["Chemical"] = 0.03,
	["Psi"] = 0,
}
ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}