ITEM.name = "SRS-E \"Eagle\" "
ITEM.model ="models/kek1ch/merc_outfit.mdl"
ITEM.replacements = "models/nasca/stalker/male_hawk_lone.mdl"
ITEM.description= "A twist on the standard mercenary suit."
ITEM.longdesc = "A variant of the Hawk suit, the Eagle sacrifices some of its secondary armors in exchange for better anomalous protection overall while keeping light."
ITEM.width = 2
ITEM.height = 1
ITEM.price = 20000
ITEM.flag = "1"
ITEM.br = 0.2
ITEM.fbr = 8
ITEM.ar = 0.05
ITEM.far = 1.5
ITEM.isArmor = true
ITEM.overlayPath = "vgui/overlays/hud_merc"
ITEM.img = Material("vgui/hud/xm40.png")
ITEM.artifactcontainers = {"2"}
ITEM.weightClass = 1
ITEM.ballisticRating = 23
ITEM.res = {
	["Impact"] = 0.06,
	["Rupture"] = 0.06,
	["Bullet"] = 0.08,
	["Shock"] = 0.05,
	["Burn"] = 0.12,
	["Radiation"] = 0.07,
	["Chemical"] = 0.05,
	["Psi"] = 0,
}

ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}