ITEM.name = "STS-N \"Nighthunter\" "
ITEM.model ="models/kek1ch/merc_outfit.mdl"
ITEM.replacements ="models/nasca/stalker/male_eagle_lone.mdl"
ITEM.description= "An elite mercenary suit."
ITEM.longdesc = "A tactical uniform issued to elite Mercenary squads operating in combat areas in the Zone's northern reaches, this outfit boasts better physical protection on top of an even better weight distribution system than its predecessor. Naturally, its price is higher than that of its lighter variant, partly due to more costly materials and supply shortages, but it largely improves on its previous design and is a perfectly serviceable combat uniform.\n\nBallistic Protection:\nTorso: III+\nLimbs: II\nWeight: 2"
ITEM.width = 2
ITEM.height = 2
ITEM.price = 80000
ITEM.flag = "A"
ITEM.br = 0.3
ITEM.fbr = 1
ITEM.ar = 0.1
ITEM.far = 0
ITEM.isGasmask = true
ITEM.isHelmet = true
ITEM.isArmor = true
ITEM.overlayPath = "vgui/overlays/hud_merc"
ITEM.img = Material("vgui/hud/xm40.png")
ITEM.artifactcontainers = {"0"}
ITEM.weight = 16
ITEM.maxArmor = 20
ITEM.res = {
	["Bullet"] = 0.4,
	["Blast"] = 0.4,
	["Fall"] = 0.4,
	["Burn"] = 0.3,
	["Radiation"] = 0.4,
	["Chemical"] = 0.2,
	["Shock"] = 0.2,
	["Psi"] = 0.0,
}

ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}