ITEM.name = "SAS-P \"Paladin\" "
ITEM.model = "models/kek1ch/exolight_outfit.mdl"
ITEM.replacements = "models/npc/stalker_merc/merc_metro/merc_metro.mdl"
ITEM.description = "A set of Paladin Assault Armor."
ITEM.longdesc = "The Mercenary answer to the Stingray, the Paladin is an older concept re-imagined using American-made armor parts intended for heavy combat in areas of moderate anomaly activity while still remaining mobile."
ITEM.width = 2
ITEM.height = 3
ITEM.price = 130000
ITEM.flag = "A"
ITEM.br = 0.6
ITEM.fbr = 11
ITEM.ar = 0.2
ITEM.far = 3
ITEM.isArmor = true
ITEM.overlayPath = "vgui/overlays/hud_merc"
ITEM.img = Material("vgui/hud/xm40.png")
ITEM.artifactcontainers = {"2"}
ITEM.noBusiness = true
ITEM.weight = 23
ITEM.weightClass = 3
ITEM.ballisticRating = 42
ITEM.res = {
	["Impact"] = 0.15,
	["Rupture"] = 0.23,
	["Bullet"] = 0.25,
	["Shock"] = 0.15,
	["Burn"] = 0.15,
	["Radiation"] = 0.09,
	["Chemical"] = 0.05,
	["Psi"] = 0.09,
}

ITEM.newSkin = 0