ITEM.name = "SAS-H \"Hawk\" "
ITEM.model ="models/kek1ch/merc_outfit.mdl"
ITEM.replacements = "models/nasca/stalker/male_hawk_lone.mdl"
ITEM.description= "A standard mercenary suit."
ITEM.longdesc = "An older suit issued to the Blue Eagle faction, made from repurposed Western special forces kit. These days, it serves fine as a light duty scouting suit, but is poorly suited for the Zone in combat and anomalies both."
ITEM.width = 2
ITEM.height = 1
ITEM.price = 15000
ITEM.flag = "1"
ITEM.br = 0.2
ITEM.fbr = 8
ITEM.ar = 0.05
ITEM.far = 1.5
ITEM.isArmor = true
ITEM.overlayPath = "vgui/overlays/hud_merc"
ITEM.img = Material("vgui/hud/xm40.png")
ITEM.artifactcontainers = {"1"}
ITEM.weight = 8
ITEM.weightClass = 1
ITEM.ballisticRating = 23
ITEM.res = {
	["Impact"] = 0.08,
	["Rupture"] = 0.11,
	["Bullet"] = 0.09,
	["Shock"] = 0.03,
	["Burn"] = 0.04,
	["Radiation"] = 0.05,
	["Chemical"] = 0.02,
	["Psi"] = 0,
}
ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}