ITEM.name = "Monolith NBC Suit (Female)"
ITEM.model = "models/kek1ch/stalker_outfit.mdl"
ITEM.replacements = "models/silver/stalker/female_nbc_mono.mdl"
ITEM.description = "A modified hazmat suit."
ITEM.longdesc = "This CBRN suit has been fitted with a tactical vest by the Monolith. Combining Monolith innovation with equipment left behind by Chernobyl liquidators after the disaster in 1986, it comes with a GP-5 gas mask connected to a modern filtering system to protect against dangerous chemicals, resulting in a Monolith uniform with increased protection compared to the standard.\n\nBallistic Protection:\nTorso: III\nLimbs: II\nWeight: 2\n\n-This item comes with a built-in Gasmask and Closed-Cycle Hood. A Helmet cannot be equipped."
ITEM.width = 2
ITEM.height = 2
ITEM.price = 55000
ITEM.flag = "3"
ITEM.br = 0.15
ITEM.fbr = 6
ITEM.ar = 0.4
ITEM.far = 3
ITEM.isGasmask = true
ITEM.isHelmet = false
ITEM.isArmor = true
ITEM.radProt = 0.4
ITEM.overlayPath = "vgui/overlays/hud_gas"
ITEM.img = Material("vgui/hud/nbc.png")
ITEM.noBusiness = true
ITEM.artifactcontainers = {"3"}
ITEM.weight = 10
ITEM.maxArmor = 20
ITEM.res = {
	["Bullet"] = 0.4,
	["Blast"] = 0.4,
	["Fall"] = 0.4,
	["Burn"] = 0.4,
	["Radiation"] = 0.7,
	["Chemical"] = 0.6,
	["Shock"] = 0.4,
	["Psi"] = 0.0,
}

ITEM.newSkin = 1
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}