ITEM.name = "NBC Suit"
ITEM.model = "models/kek1ch/stalker_outfit.mdl"
ITEM.replacements = "models/nasca/stalker/male_nbc_lone.mdl"
ITEM.description = "A modified hazmat suit."
ITEM.longdesc = "A budget CBRN suit fitted with a kevlar vest, this suit is assembled by stalkers looking for enhanced protection against the Zone's environment at an affordable cost. It comes standard with a GP-5 gas mask using a hose leading to a modern filter. Although clearly hobbled together from various parts, it's nonetheless a popular choice among those who appreciate increased anomalous protection.\n\nBallistic Protection:\nTorso: IIA\nLimbs: IIA\nWeight: 2\n\n-This item comes with a built-in Gasmask and Closed-Cycle Hood. A Helmet cannot be equipped."
ITEM.width = 2
ITEM.height = 2
ITEM.price = 16000
ITEM.flag = "3"
ITEM.br = 0.15
ITEM.fbr = 6
ITEM.ar = 0.4
ITEM.far = 3
ITEM.isHelmet = false
ITEM.isGasmask = true
ITEM.isArmor = true
ITEM.radProt = 0.3
ITEM.overlayPath = "vgui/overlays/hud_gas"
ITEM.img = Material("vgui/hud/nbc.png")
ITEM.artifactcontainers = {"3"}
ITEM.weight = 12
ITEM.maxArmor = 10
ITEM.res = {
	["Bullet"] = 0.2,
	["Blast"] = 0.2,
	["Fall"] = 0.2,
	["Burn"] = 0.2,
	["Radiation"] = 0.3,
	["Chemical"] = 0.3,
	["Shock"] = 0.2,
	["Psi"] = 0,
}

ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}