ITEM.name = "PSZ-9d Universal Protection (Female)" 
ITEM.model = "models/kek1ch/stalker_outfit.mdl"
ITEM.replacements = "models/nasca/stalker/female_psz9d_duty.mdl"
ITEM.description= "A PSZ-9 suit commissioned by Duty." 
ITEM.longdesc = "This bodysuit was produced by one of Kiev's defense research institutes and was primarily commissioned by the Duty faction, who issue it as their standard uniform. Its use of cutting-edge materials provides decent protection against low-calibre firearms. Meanwhile, it provides adequate protection against anomalies, making it a well-rounded suit."
ITEM.width = 2
ITEM.height = 2
ITEM.price = 25000
ITEM.flag = "3"
ITEM.br = 0.2
ITEM.fbr = 7
ITEM.ar = 0.2
ITEM.far = 3
ITEM.isGasmask = true
ITEM.isHelmet = true
ITEM.isArmor = true
ITEM.artifactcontainers = {"2"}
ITEM.overlayPath = "vgui/overlays/hud_gas"
ITEM.img = Material("vgui/hud/eo20.png")
ITEM.noBusiness = true
ITEM.weightClass = 2
ITEM.ballisticRating = 36
ITEM.res = {
	["Impact"] = 0.16,
	["Rupture"] = 0.22,
	["Bullet"] = 0.15,
	["Shock"] = 0.04,
	["Burn"] = 0.10,
	["Radiation"] = 0.06,
	["Chemical"] = 0.04,
	["Psi"] = 0,
}

ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}