ITEM.name = "PSZ-9 Universal Protection (Female)" 
ITEM.model = "models/kek1ch/stalker_outfit.mdl"
ITEM.replacements = "models/nasca/stalker/female_midnight_lone.mdl"
ITEM.description= "A Loner variant of the PSZ-9d suit." 
ITEM.longdesc = "This bodysuit was produced by one of Kiev's defense research institutes and was primarily commissioned by the Duty faction, who issue it as their standard uniform. Its use of cutting-edge materials provides decent protection against low-calibre firearms. Meanwhile, it provides adequate protection against anomalies, making it a well-rounded suit."
ITEM.width = 2
ITEM.height = 2
ITEM.price = 25000
ITEM.flag = "3"
ITEM.br = 0.2
ITEM.fbr = 7
ITEM.ar = 0.2
ITEM.far = 3
ITEM.isGasmask = true
ITEM.isHelmet = true
ITEM.isArmor = true
ITEM.overlayPath = "vgui/overlays/hud_gas"
ITEM.img = Material("vgui/hud/eo20.png")
ITEM.artifactcontainers = {"2"}
ITEM.weightClass = 2
ITEM.ballisticRating = 26
ITEM.res = {
	["Impact"] = 0.10,
	["Rupture"] = 0.17,
	["Bullet"] = 0.09,
	["Shock"] = 0.12,
	["Burn"] = 0.31,
	["Radiation"] = 0.08,
	["Chemical"] = 0.08,
	["Psi"] = 0,
}

ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}