ITEM.name = "PSZ-12d Duty Armor" 
ITEM.model = "models/kek1ch/spec_sold_outfit.mdl"
ITEM.replacements = "models/nasca/stalker/male_psz12d_duty.mdl"
ITEM.description= "A prototype Spetsnaz armored suit."
ITEM.longdesc = "This armor consists of some of the earliest armor used by Duty within the Zone. The suit is capable of stopping many ballistic threats, however, this level of protection comes at the cost of its weight, bulkiness and, next to its later Stingray younger brothers, vastly inferior anomaly protection. It has a legendary reputation as the uniform of some of Duty's most prominent veterans."
ITEM.width = 2
ITEM.height = 3
ITEM.price = 125000
ITEM.flag = "4"
ITEM.br = 0.4
ITEM.fbr = 9
ITEM.ar = 0.15
ITEM.far = 2
ITEM.isArmor = true
ITEM.overlayPath = "vgui/overlays/hud_merc"
ITEM.img = Material("vgui/hud/xm40.png")
ITEM.noBusiness = true
ITEM.artifactcontainers = {"0"}
ITEM.weight = 23
ITEM.weightClass = 3
ITEM.ballisticRating = 45
ITEM.res = {
	["Impact"] = 0.28,
	["Rupture"] = 0.26,
	["Bullet"] = 0.30,
	["Shock"] = 0.12,
	["Burn"] = 0.45,
	["Radiation"] = 0.07,
	["Chemical"] = 0.09,
	["Psi"] = 0.05,
}

ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}