ITEM.name = "Sentinel of Freedom (Female)" 
ITEM.model = "models/kek1ch/stalker_outfit.mdl"
ITEM.replacements = "models/nasca/stalker/female_psz9d_free.mdl"
ITEM.description= "A PSZ-9 suit used by Freedom." 
ITEM.longdesc = "This PSZ-9 suit is issued to the majority of Freedom members. It is roughly comparable to the suits used by many stalkers, along with those of their rivals in Duty. It boasts decent protection against firearms and anomalies and is very comfortable to wear."
ITEM.width = 2
ITEM.height = 2
ITEM.price = 36000
ITEM.flag = "3"
ITEM.br = 0.2
ITEM.fbr = 7
ITEM.ar = 0.2
ITEM.far = 3
ITEM.isGasmask = true
ITEM.isHelmet = true
ITEM.isArmor = true
ITEM.overlayPath = "vgui/overlays/hud_gas"
ITEM.img = Material("vgui/hud/eo20.png")
ITEM.noBusiness = true
ITEM.artifactcontainers = {"3"}
ITEM.weightClass = 1
ITEM.ballisticRating = 36
ITEM.res = {
	["Impact"] = 0.10,
	["Rupture"] = 0.14,
	["Bullet"] = 0.13,
	["Shock"] = 0.05,
	["Burn"] = 0.12,
	["Radiation"] = 0.06,
	["Chemical"] = 0.05,
	["Psi"] = 0,
}

ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}