ITEM.name = "PSZ-12d Duty Armor" 
ITEM.model = "models/kek1ch/spec_sold_outfit.mdl"
ITEM.replacements = "models/nasca/stalker/male_psz12d_duty.mdl"
ITEM.description= "A prototype Spetsnaz armored suit."
ITEM.longdesc = "This armor consists of some of the earliest armor used by Duty within the Zone. The suit is capable of stopping many ballistic threats, however, this level of protection comes at the cost of its weight, bulkiness and virtually non-existent anomaly protection. It has a legendary reputation as the uniform of some of Duty's most prominent veterans.\n\nBallistic Protection:\nSkull: III+\nNeck & Face: IIIA\nTorso: IV\nLimbs: III\nWeight: 3"
ITEM.width = 2
ITEM.height = 3
ITEM.price = 125000
ITEM.flag = "4"
ITEM.br = 0.4
ITEM.fbr = 9
ITEM.ar = 0.15
ITEM.far = 2
ITEM.isGasmask = true
ITEM.isHelmet = false
ITEM.isArmor = true
ITEM.overlayPath = "vgui/overlays/hud_merc"
ITEM.img = Material("vgui/hud/xm40.png")
ITEM.noBusiness = true
ITEM.artifactcontainers = {"0"}
ITEM.weight = 23
ITEM.maxArmor = 40
ITEM.res = {
	["Bullet"] = 0.7,
	["Blast"] = 0.7,
	["Fall"] = 0.7,
	["Burn"] = 0.3,
	["Radiation"] = 0.4,
	["Chemical"] = 0.3,
	["Shock"] = 0.2,
	["Psi"] = 0.0,
}

ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}