ITEM.name = "'Vulture' PSZ Suit" 
ITEM.model = "models/kek1ch/stalker_outfit.mdl"
ITEM.replacements = "models/player/stalker_bandit/bandit_old/bandit_old.mdl"
ITEM.description= "A Bandit-created PSZ suit." 
ITEM.longdesc = "This bodysuit was once a PSZ-9 or another faction's variant, sold to or looted by Bandits and when damaged in combat, repaired with whatever could be found. The end result is a weird suit nonetheless used for lighter skirmishes."
ITEM.width = 2
ITEM.height = 2
ITEM.price = 30000
ITEM.flag = "3"
ITEM.br = 0.2
ITEM.fbr = 7
ITEM.ar = 0.2
ITEM.far = 3
ITEM.isArmor = true
ITEM.overlayPath = "vgui/overlays/hud_gas"
ITEM.img = Material("vgui/hud/eo20.png")
ITEM.artifactcontainers = {"1"}
ITEM.weightClass = 2
ITEM.ballisticRating = 36
ITEM.res = {
	["Impact"] = 0.06,
	["Rupture"] = 0.16,
	["Bullet"] = 0.12,
	["Shock"] = 0.05,
	["Burn"] = 0.10,
	["Radiation"] = 0.02,
	["Chemical"] = 0.02,
	["Psi"] = 0,
}

ITEM.newSkin = 1
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}