ITEM.name = "TB-3 Exosuit"
ITEM.model = "models/kek1ch/exolight_outfit.mdl"
ITEM.replacements = "models/nasca/stalker/male_exo_lone.mdl"
ITEM.description = "A set of TB-3 heavy armor."
ITEM.longdesc = "The base component of many third-generation exoskeletons, this suit consists of a heavy armored vest and a reinforced environmental jumpsuit. While mistakenly referred to as a radiation suit, this outfit actually eschews most environmental protection in favor of raw combat potential. It is used by many veteran stalkers in the most dangerous parts of the Zone."
ITEM.width = 3
ITEM.height = 3
ITEM.price = 175000
ITEM.flag = "A"
ITEM.br = 0.6
ITEM.fbr = 11
ITEM.ar = 0.2
ITEM.far = 3
ITEM.isArmor = true
ITEM.overlayPath = "vgui/overlays/hud_merc"
ITEM.img = Material("vgui/hud/xm40.png")
ITEM.artifactcontainers = {"2"}
ITEM.noBusiness = true
ITEM.weight = 26
ITEM.weightClass = 4
ITEM.ballisticRating = 50
ITEM.res = {
	["Impact"] = 0.28,
	["Rupture"] = 0.30,
	["Bullet"] = 0.31,
	["Shock"] = 0.07,
	["Burn"] = 0.01,
	["Radiation"] = 0.06,
	["Chemical"] = 0.02,
	["Psi"] = 0,
}
ITEM.newSkin = 0
ITEM.bodyGroups = {
	["Servomotors"] = 1,
}