ITEM.name ="R-1 Scout Armor"
ITEM.model ="models/kek1ch/cs_light_outfit.mdl"
ITEM.replacements ="models/nasca/stalker/male_cs1a.mdl"
ITEM.description="A Renegade scouting suit."
ITEM.longdesc = "A light suit once used by Clear Sky, and hijacked by the Renegades for their own purposes. Showing their superior resources early into the faction war, it offers all-round better protection than the origonal counterpart. \n\nBallistic Protection:\nTorso: III\nLimbs: II\nWeight: 2"
ITEM.width = 2
ITEM.height = 2
ITEM.price = 38000
ITEM.flag = "A"
ITEM.br = 0.18
ITEM.fbr = 1
ITEM.ar = 0.15
ITEM.far = 1
ITEM.isArmor = true
ITEM.isHelmet = true
ITEM.repairCost = ITEM.price/100*1
ITEM.img = Material("vgui/hud/cs1.png")
ITEM.artifactcontainers = {"3"}
ITEM.weight = 15
ITEM.maxArmor = 10
ITEM.res = {
	["Bullet"] = 0.4,
	["Blast"] = 0.4,
	["Fall"] = 0.4,
	["Burn"] = 0.4,
	["Radiation"] = 0.4,
	["Chemical"] = 0.4,
	["Shock"] = 0.4,
	["Psi"] = 0.0,
}

ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}