ITEM.name = "Duty TB-3 Exosuit"
ITEM.model ="models/kek1ch/exolight_outfit.mdl"
ITEM.replacements ="models/nasca/stalker/male_exo_duty.mdl"
ITEM.description= "A set of TB-3 heavy armor."
ITEM.longdesc = "This suit of armor was originally created for military use but never entered mass production due to prohibitive costs and design problems. Nonetheless, Duty makes use of it due to its excellent protective qualities in combat. Faction technicians have modified the suit, sacrificing space for artifacts in favor of even heavier armor."
ITEM.width = 2
ITEM.height = 4
ITEM.price = 230
ITEM.flag = "A"
ITEM.br = 0.6
ITEM.fbr = 11
ITEM.ar = 0.2
ITEM.far = 3
ITEM.isArmor = true
ITEM.artifactcontainers = {"2"}
ITEM.overlayPath = "vgui/overlays/hud_merc"
ITEM.img = Material("vgui/hud/xm40.png")
ITEM.noBusiness = true
ITEM.weight = 30
ITEM.weightClass = 4
ITEM.ballisticRating = 57
ITEM.res = {
	["Impact"] = 0.33,
	["Rupture"] = 0.33,
	["Bullet"] = 0.39,
	["Shock"] = 0,
	["Burn"] = 0.03,
	["Radiation"] = 0.05,
	["Chemical"] = 0.05,
	["Psi"] = 0,
}
ITEM.newSkin = 0
ITEM.bodyGroups = {
	["servomotors"] = 1,
}