ITEM.name = "SSP-99M Ecologist Suit"
ITEM.model = "models/kek1ch/ecolog_outfit_green.mdl"
ITEM.replacements = "models/nasca/stalker/male_ssp_eco.mdl"
ITEM.description= "An advanced environmental suit."
ITEM.longdesc = "A high quality modified SSP-99 suit. It provides increased body protection from bullet and splinter damage. It is designed for the guards working with scientific expeditions. It provides good protection from radiation and biological anomalies. It is resistant to chemically aggressive environments and other effects dangerous to the body."
ITEM.width = 2
ITEM.height = 2
ITEM.price = 150000
ITEM.flag = "A"
ITEM.br = 0.2
ITEM.fbr = 5
ITEM.ar = 0.8
ITEM.far = 6
ITEM.isArmor = true
ITEM.radProt = 0.8
ITEM.repairCost = ITEM.price/100*1
ITEM.overlayPath = "vgui/overlays/hud_sci"
ITEM.img = Material("vgui/hud/ssp99m.png")
ITEM.noBusiness = true
ITEM.artifactcontainers = {"5"}
ITEM.weightClass = 2
ITEM.ballisticRating = 15
ITEM.res = {
	["Impact"] = 0.11,
	["Rupture"] = 0.12,
	["Bullet"] = 0.08,
	["Shock"] = 0.26,
	["Burn"] = 0.76,
	["Radiation"] = 0.10,
	["Chemical"] = 0.17,
	["Psi"] = 0.10,
}
ITEM.newSkin = 1
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}