ITEM.name = "Volos Flak Armor" 
ITEM.model = "models/kek1ch/stalker_outfit.mdl"
ITEM.replacements = "models/player/stalker_greh/greh_sunrise/greh_sunrise.mdl"
ITEM.description= "A modified PSZ-9 suit."
ITEM.longdesc = "What looks to be a PSZ-9 suit or some variant thereof, visibly worn down and repaired using whichever could be found. It's of unusual quality among its peers, with some parts superior and some vastly worse, but is still often found used by Sinners as one of its standard issues, and they don't seem too concerned about it. "
ITEM.width = 2
ITEM.height = 1
ITEM.price = 15000
ITEM.flag = "A"
ITEM.br = 0.2
ITEM.fbr = 8
ITEM.ar = 0.05
ITEM.far = 1.5
ITEM.isArmor = true
ITEM.overlayPath = "vgui/overlays/hud_merc"
ITEM.img = Material("vgui/hud/xm40.png")
ITEM.artifactcontainers = {"2"}
ITEM.weight = 8
ITEM.weightClass = 2
ITEM.ballisticRating = 30
ITEM.res = {
	["Impact"] = 0.28,
	["Rupture"] = 0.12,
	["Bullet"] = 0.12,
	["Shock"] = 0.25,
	["Burn"] = 0,
	["Radiation"] = 0.06,
	["Chemical"] = 0.10,
	["Psi"] = 0,
}
ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}