ITEM.name = "Sunset Lightweight Assault Suit (Female)"
ITEM.model = "models/kek1ch/exolight_outfit.mdl"
ITEM.replacements = "models/silver/stalker/female_sunset_lone.mdl"
ITEM.description = "A set of Sunset Assault Armour."
ITEM.longdesc = "A traditional 'Sunrise' stalker suit that has been heavily modified with non-traditional components, this suit consists of a base suit that has been supplemented and armoured with various pieces of body armour. It's not seen often in the hands of Stalkers in the zone due to the rare components needed to manufacture it, but it is used by Veteran stalkers as an efficient combat suit that can prove versatile in countless situations.\n\nBallistic Protection:\nTorso: III\nLimbs: II\nWeight: 2"
ITEM.width = 2
ITEM.height = 2
ITEM.price = 35000
ITEM.flag = "A"
ITEM.br = 0.6
ITEM.fbr = 11
ITEM.ar = 0.2
ITEM.far = 3
ITEM.isGasmask = true
ITEM.isHelmet = true
ITEM.isArmor = true
ITEM.overlayPath = "vgui/overlays/hud_merc"
ITEM.img = Material("vgui/hud/xm40.png")
ITEM.artifactcontainers = {"2"}
ITEM.noBusiness = true
ITEM.weight = 15
ITEM.maxArmor = 30
ITEM.res = {
	["Bullet"] = 0.4,
	["Blast"] = 0.4,
	["Fall"] = 0.4,
	["Burn"] = 0.2,
	["Radiation"] = 0.4,
	["Chemical"] = 0.2,
	["Shock"] = 0.0,
	["Psi"] = 0.0,
}

ITEM.newSkin = 0