ITEM.name = "Sin Heavy Overcoat"
ITEM.model = "models/kek1ch/novice_outfit.mdl"
ITEM.replacements = "models/player/stalker_greh/greh_cloak/greh_cloak.mdl"
ITEM.description= "A cobbled-together suit worn under a thick coat."
ITEM.longdesc = "The worn remains of a PSZ or SEVA suit, put together with whatever could be found, likely scavenged from defeated enemies of Sin. It's not the best suit out there, but it works."
ITEM.width = 2
ITEM.height = 1
ITEM.price = 14000
ITEM.flag = "A"
ITEM.br = 0.2
ITEM.fbr = 8
ITEM.ar = 0.05
ITEM.far = 1.5
ITEM.isArmor = true
ITEM.overlayPath = "vgui/overlays/hud_merc"
ITEM.img = Material("vgui/hud/xm40.png")
ITEM.artifactcontainers = {"1"}
ITEM.weightClass = 1
ITEM.ballisticRating = 22
ITEM.res = {
	["Impact"] = 0.15,
	["Rupture"] = 0.16,
	["Bullet"] = 0.10,
	["Shock"] = 0.05,
	["Burn"] = 0.12,
	["Radiation"] = 0.02,
	["Chemical"] = 0.03,
	["Psi"] = 0.06,
}
ITEM.newSkin = 8
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}