ITEM.name = "Stingray-9M Armored Suit"
ITEM.model = "models/kek1ch/military_outfit.mdl"
ITEM.replacements = "models/nasca/stalker/male_stingray9m.mdl"
ITEM.description= "SKAT-9M suit." 
ITEM.longdesc = "This bulletproof military suit innovates on the previous Stingray-9 design tooled for operations near the center of the Zone. It includes a heavy military bulletproof suit and an integrated compensation suit. It provides excellent protection from bullets and splinters and it doesn't decrease the soldier's mobility, while retaining a balanced system of anomaly protection. It is rarely seen out of highly specialized Spetsnaz operatives and military stalkers."
ITEM.width = 2
ITEM.height = 3
ITEM.price = 180000
ITEM.flag = "A"
ITEM.br = 0.35
ITEM.fbr = 10
ITEM.ar = 0.28
ITEM.far = 3
ITEM.isArmor = true
ITEM.repairCost = ITEM.price/100*1
ITEM.overlayPath = "vgui/overlays/hud_merc"
ITEM.img = Material("vgui/hud/xm40.png")
ITEM.noBusiness = true
ITEM.artifactcontainers = {"2"}
ITEM.weight = 22
ITEM.weightClass = 3
ITEM.ballisticRating = 50
ITEM.res = {
	["Impact"] = 0.28,
	["Rupture"] = 0.26,
	["Bullet"] = 0.30,
	["Shock"] = 0.30,
	["Burn"] = 0.50,
	["Radiation"] = 0.10,
	["Chemical"] = 0.15,
	["Psi"] = 0.10,
}
ITEM.newSkin = 0
ITEM.bodyGroups = {
	["helmet"] = 1,
}