ITEM.name = "Vyriy Flak Armor" 
ITEM.model ="models/kek1ch/merc_outfit.mdl"
ITEM.replacements = "models/player/stalker_greh/greh_gear/greh_gear.mdl"
ITEM.description= "A former mercenary suit."
ITEM.longdesc = "What looks to be a Hawk suit or some variant thereof with some extra, surprisingly heavy armor plating installed, issued to members of Sin for unknown roles, but presumably for light skirmishing."
ITEM.width = 2
ITEM.height = 1
ITEM.price = 15000
ITEM.flag = "1"
ITEM.br = 0.2
ITEM.fbr = 8
ITEM.ar = 0.05
ITEM.far = 1.5
ITEM.isArmor = true
ITEM.overlayPath = "vgui/overlays/hud_merc"
ITEM.img = Material("vgui/hud/xm40.png")
ITEM.artifactcontainers = {"2"}
ITEM.weight = 8
ITEM.weightClass = 2
ITEM.ballisticRating = 26
ITEM.res = {
	["Impact"] = 0.10,
	["Rupture"] = 0.10,
	["Bullet"] = 0.11,
	["Shock"] = 0.06,
	["Burn"] = 0.06,
	["Radiation"] = 0.03,
	["Chemical"] = 0.06,
	["Psi"] = 0,
}
ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}