ITEM.name = "\"Sunrise\" Stalker Suit (Female)"
ITEM.model = "models/kek1ch/stalker_outfit.mdl"
ITEM.replacements = "models/nasca/stalker/female_sunrise_lone.mdl"
ITEM.description = "A standard stalker outfit."
ITEM.longdesc = "This DIY suit is made of twin-layered rubberised cloth with plexiglass lining and integrated body armor. It is the quintessential outfit of a stalker, and despite not being very protective, it enjoys immense popularity among rookies and veteran stalkers alike thanks to its economical use and great modification potential."
ITEM.width = 2
ITEM.height = 1
ITEM.price = 10000
ITEM.flag = "1"
ITEM.br = 0.15
ITEM.fbr = 6
ITEM.ar = 0.15
ITEM.far = 2
ITEM.isArmor = true
ITEM.repairCost = ITEM.price/100*1
ITEM.overlayPath = "vgui/overlays/hud_gas"
ITEM.img = Material("vgui/hud/eo20.png")
ITEM.artifactcontainers = {"2"}
ITEM.weight = 7
ITEM.maxArmor = 10
ITEM.weightClass = 1
ITEM.ballisticRating = 20
ITEM.res = {
	["Impact"] = 0.13,
	["Rupture"] = 0.16,
	["Bullet"] = 0.09,
	["Shock"] = 0.06,
	["Burn"] = 0.14,
	["Radiation"] = 0.07,
	["Chemical"] = 0.04,
	["Psi"] = 0.00,
}

ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}