ITEM.name = "Stingray-9 Armored Suit"
ITEM.model = "models/kek1ch/military_outfit.mdl"
ITEM.replacements = "models/nasca/stalker/male_stingray9_lone.mdl"
ITEM.description= "SKAT-9 suit." 
ITEM.longdesc = "An excellent protective suit for the Zone. This heavy military-grade armor was designed for major assault operations in anomalous areas. It comprises a PSZ-12 heavy military armored vest, built-in compensation system, and an anomalous protection bodysuit. The armor affords great protection against bullet and fragmentation damage, without greatly reducing the wearer's mobility. This uniform is issued primarily to military stalkers and Spetsnaz operatives who use it for operations deep in the Zone."
ITEM.width = 2
ITEM.height = 3
ITEM.price = 100000
ITEM.flag = "A"
ITEM.br = 0.35
ITEM.fbr = 10
ITEM.ar = 0.28
ITEM.far = 3
ITEM.isArmor = true
ITEM.repairCost = ITEM.price/100*1
ITEM.overlayPath = "vgui/overlays/hud_merc"
ITEM.img = Material("vgui/hud/xm40.png")
ITEM.noBusiness = true
ITEM.artifactcontainers = {"1"}
ITEM.weight = 18
ITEM.weightClass = 3
ITEM.ballisticRating = 40
ITEM.res = {
	["Impact"] = 0.28,
	["Rupture"] = 0.23,
	["Bullet"] = 0.28,
	["Shock"] = 0.17,
	["Burn"] = 0.41,
	["Radiation"] = 0.10,
	["Chemical"] = 0.09,
	["Psi"] = 0.08,
}
ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}