ITEM.name = "Trenchcoat"
ITEM.model = "models/kek1ch/novice_outfit.mdl"
ITEM.replacements = "models/nasca/stalker/male_trenchcoat.mdl"
ITEM.description= "A long overcoat."
ITEM.longdesc = "A long, thick overcoat. The protection offered by this apparel can vary tremendously depending on the tailor, but as a general rule it is only slightly less useless than the leather jacket. Still, many newer stalkers will swear by it simply because it looks cool."
ITEM.width = 2
ITEM.height = 1
ITEM.price = 5000
ITEM.flag = "1"
ITEM.br = 0.05
ITEM.fbr = 3
ITEM.ar = 0.05
ITEM.far = 1
ITEM.repairCost = ITEM.price/100*1
ITEM.isArmor = true
ITEM.img = Material("vgui/hud/trenchcoat.png")
ITEM.artifactcontainers = {"0"}
ITEM.weight = 4
ITEM.weightClass = 1
ITEM.ballisticRating = 12
ITEM.res = {
	["Impact"] = 0.01,
	["Rupture"] = 0.11,
	["Bullet"] = 0.01,
	["Shock"] = 0.06,
	["Burn"] = 0.11,
	["Radiation"] = 0.03,
	["Chemical"] = 0.05,
	["Psi"] = 0.06,
}

ITEM.newSkin = 4
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}