ITEM.name = "Armor Plating Scrap"
ITEM.model = "models/mosi/fallout4/props/junk/components/glass.mdl"
ITEM.description = "Chunks of metal broken off plate carriers. Not much use on its own, but can be a component in hard plate armors."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 500
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 5
