ITEM.name = "Lightbulb"
ITEM.model = "models/illusion/eftcontainers/lightbulb.mdl"
ITEM.description = "An intact Lightbulb, fit to be screwed into an outlet and lit up."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 150
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 0.1