ITEM.name = "Broken Headlamp"
ITEM.model = "models/jerry/headtorch.mdl"
ITEM.description = "A Headlamp with a busted bulb in its socket."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 600
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 0.25