ITEM.name = "Canvas Scrap"
ITEM.model = "models/mosi/fallout4/props/junk/components/cloth.mdl"
ITEM.description = "A bit of plastic canvas, at times used for being resistant to acidic substances."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 125
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 0.25
