ITEM.name = "Ceramic Scrap"
ITEM.model = "models/mosi/fallout4/props/junk/components/ceramic.mdl"
ITEM.description = "Bits of ceramic plating, used in hard armors as a lighter but less durable alternative."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 5
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 1
