ITEM.name = "Cloth Scrap"
ITEM.model = "models/mosi/fallout4/props/junk/components/cloth.mdl"
ITEM.description = "A bit of cloth, used sometimes in makeshift bandages or suits."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 25
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 0.01
