ITEM.name = "Car Battery"
ITEM.model = "models/illusion/eftcontainers/carbattery.mdl"
ITEM.description = "A standard, hefty, lead car-battery made to power a vehicle's electrical components. This one seems to be functional with a decent bit of juice left in it."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 15000
ITEM.width = 3
ITEM.height = 2
ITEM.weight = 20