ITEM.name = "Carved Cat Statue"
ITEM.model = "models/illusion/eftcontainers/catfigurine.mdl"
ITEM.description = "A hand-carved, smoothed, and polished cat figurine. These used to be a relatively common art piece in the Chernobyl Area before the disaster, a trend if anything. Most are scavenged now as unique antiques."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 2000
ITEM.width = 1
ITEM.height = 2
ITEM.weight = 0.01