ITEM.name = "Damaged PDA"
ITEM.model = "models/kek1ch/dev_pda.mdl"
ITEM.description = "Damaged PDA that refuses to turn on. Could be worth something."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 600
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 0.8