ITEM.name = "Explosive Material"
ITEM.model = "models/illusion/eftcontainers/gpred.mdl"
ITEM.description = "A jarred container of synthesized material often harvested from undetonated Soviet munitions strewn about the Exclusion Zone. Various groups and Stalkers utilize said material for making proper explosives. Such a reagent seems to be shock-resistant despite its combustible nature, and despite being flammable it poses not explosive threat unless properly detonated."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 6500
ITEM.width = 1
ITEM.height = 2
ITEM.weight = 0.01