ITEM.name = "Ecologist Patch"
ITEM.model = "models/silver/stalker/items/tfw_scientist.mdl"
ITEM.description = "A patch that once belonged to a member of the Ecologists faction."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 3500
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 0.01
