ITEM.name = "Ecologist Sample"
ITEM.model = "models/illusion/eftcontainers/bloodsample.mdl"
ITEM.description = "A small, full vial of... something. Unsure of what it contains, it does have a little white card strung to its cap defining the date it was taken, the admitting Researcher, and the attached log-file's ID number.. Which isn't present. Perhaps they'd be happy to get this back."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 2500
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 0.01