ITEM.name = "Gasmask Filter"
ITEM.model = "models/teebeutel/metro/objects/gasmask_filter.mdl"
ITEM.description = "A small, handheld, carbon-based filter fit to be screwed onto various open-filtering Gas-Masks."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 2500
ITEM.width = 2
ITEM.height = 1
ITEM.weight = 0.01