ITEM.name = "Iron Pan"
ITEM.model = "models/props_c17/metalPot002a.mdl"
ITEM.description = "A rusty cast-iron pan used for cooking."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 250
ITEM.width = 2
ITEM.height = 1
ITEM.weight = 3