ITEM.name = "Industrial Filter"
ITEM.model = "models/illusion/eftcontainers/airfilter.mdl"
ITEM.description = "A hefty, rusted carbon-filter from an Industrial complex of sorts. Heavy, and kind of a pain to drag around, but still contains unperishable, fine-filtering carbon. Utilized in factories usually to keep air quality within legal limits for workers."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 25000
ITEM.width = 3
ITEM.height = 3
ITEM.weight = 0.01