ITEM.name = "Lighter Fluid"
ITEM.model = "models/kek1ch/lighter_refiller.mdl"
ITEM.description = "A can of lighter fluid, used to refill lighters or by itself as a means to make things extra flammable. 9/10 arsonists reccomend."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 1800
ITEM.width = 1
ITEM.height = 2
ITEM.weight = 0.2