ITEM.name = "Metal Mesh"
ITEM.model = "models/mosi/fallout4/props/junk/components/fiberoptic.mdl"
ITEM.description = "A bit of metal mesh, valued for its electric dispersion and psionic protection capabilities, depending on how you use it."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 500
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 1.5
