ITEM.name = "Military Grade Transmitter"
ITEM.model = "models/illusion/eftcontainers/controller.mdl"
ITEM.description = "A modernized transmitter device utilized by shady-entities stalking the Zone and the Ukrainian Military. Pretty useless without its encryption keys or fair bit of other equipment to hook it up to, but valuable."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 30000
ITEM.width = 2
ITEM.height = 2
ITEM.weight = 0.01