ITEM.name = "Metal Scraps"
ITEM.model = "models/mosi/fallout4/props/junk/modbox.mdl"
ITEM.description = "A pile of random pieces of scrap metal, used in some creations or cheap sell fodder."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 10
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 1
