ITEM.name = "Rubber Scrap"
ITEM.model = "models/mosi/fallout4/props/junk/components/rubber.mdl"
ITEM.description = "A bit of rubber, used most often in suits and creating weapon suppressors."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 125
ITEM.width = 1
ITEM.height = 1
ITEM.height = 1
