ITEM.name = "Rope"
ITEM.model = "models/kek1ch/rope.mdl"
ITEM.description = "A standard roll of rope. Very useful for taking mutant bounties in alive or tying up unwilling captives. Very flammable, but sturdy."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 650
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 2