ITEM.name = "Solid State Drive"
ITEM.model = "models/illusion/eftcontainers/flashstorage.mdl"
ITEM.description = "A solid state drive that appears to be in decent condition. A piece of preferred tech compared to its Hard drive counterpart on higher-grade computers."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 10000
ITEM.width = 2
ITEM.height = 1
ITEM.weight = 0.01