ITEM.name = "Western Advanced Weapon Parts"
ITEM.model = "models/illusion/eftcontainers/weaponparts.mdl"
ITEM.description = "A pile of weapon parts belonging to western weaponry that require notably high durability or precision parts, generally used in sniper rifles and machine guns."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 2500
ITEM.width = 2
ITEM.height = 1
ITEM.weight = 2