ITEM.name = "Soviet Rifle Weapon Parts"
ITEM.model = "models/illusion/eftcontainers/weaponparts.mdl"
ITEM.description = "A pile of weapon parts belonging to older rifle variants of the AK series. Could be useful to some."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 750
ITEM.width = 2
ITEM.height = 1
ITEM.weight = 0.8