ITEM.name = "Soviet Small Arms Weapon Parts"
ITEM.model = "models/illusion/eftcontainers/weaponparts.mdl"
ITEM.description = "A pile of weapon parts belonging to Warsaw Pact weaponry of small caliber, such as pistols, SMGs, and shotguns."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 250
ITEM.width = 2
ITEM.height = 1
ITEM.weight = 0.2