ITEM.name = "Synthetic Weapon Parts"
ITEM.model = "models/illusion/eftcontainers/weaponparts.mdl"
ITEM.description = "A pile of newer weapon parts made of polymer, a lighter material that absorbs more recoil that replaces some metal or wood parts. Used in more recent Warsaw and NATO weapons alike."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 3000
ITEM.width = 2
ITEM.height = 1
ITEM.weight = 0.4