ITEM.name = "Soviet Advanced Weapon Parts"
ITEM.model = "models/illusion/eftcontainers/weaponparts.mdl"
ITEM.description = "A pile of weapon parts belonging to soviet or post-soviet weaponry that require notably high durability or precision parts, generally used in sniper rifles and machine guns."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 1000
ITEM.width = 2
ITEM.height = 1
ITEM.weight = 2