ITEM.name = "Western Rifle Weapon Parts"
ITEM.model = "models/illusion/eftcontainers/weaponparts.mdl"
ITEM.description = "A pile of weapon parts belonging to western-based rifles and certain battle rifles."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 2000
ITEM.width = 2
ITEM.height = 1
ITEM.weight = 1