ITEM.name = "Water Purification Tablets"
ITEM.model = "models/kek1ch/drug_radioprotector.mdl"
ITEM.description = "A blister pack with two pills for purifying water. Simply boil contaminated water, drop both tablets in, and let dissolve. Very common, handy, and cheap."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 10
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 0.01