ITEM.name = "NATO Small Arms Weapon Parts"
ITEM.model = "models/illusion/eftcontainers/weaponparts.mdl"
ITEM.description = "A pile of weapon parts belonging to small-caliber NATO weaponry like pistols, SMGs, or shotguns."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 750
ITEM.width = 2
ITEM.height = 1
ITEM.weight = 0.600