ITEM.name = "AA Battery"
ITEM.model = "models/illusion/eftcontainers/aabattery.mdl"
ITEM.description = "It's a double-ayy battery, used to power many electronics. Looks to still have juice in it. Do not lick."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 100
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 0.01
ITEM.quantity = 1