ITEM.name = "23x75mm Penetrator"
ITEM.model = "models/kek1ch/ammo_12x70_buck.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.ammo = "23mm Shell Slug"
ITEM.description = "A Box that contains %s 23mm Penetrator shells."
ITEM.category = "Ammunition"
ITEM.price = 10000
ITEM.flag = "4"
ITEM.ammoAmount = 5
ITEM.weight = 2
ITEM.isAmmo = true