ITEM.name = ".38 Special Match Grade"
ITEM.model = "models/kek1ch/ammo_9x18_fmj.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.ammoAmount = 30
ITEM.ammo = ".38 Special -MG-" // type of the ammo
ITEM.description = "A box that contains .38 Special. This box was made to a higher standard for improved performance and a flatter trajectory."
ITEM.category = "Ammunition"
ITEM.price = 450
ITEM.flag = "A"
ITEM.weight = 0.2
ITEM.isAmmo = true