ITEM.name = ".38 Special Hollow-Point"
ITEM.model = "models/kek1ch/ammo_9x18_fmj.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.ammoAmount = 30
ITEM.ammo = ".38 Special -HP-" // type of the ammo
ITEM.description = "A Box that contains .38 Special"
ITEM.category = "Ammunition"
ITEM.price = 300
ITEM.flag = "1"
ITEM.weight = 0.2
ITEM.isAmmo = true