ITEM.name = ".357 Magnum Zone-Loaded"
ITEM.model = "models/ethprops/ammo/357.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.ammo = ".357 -ZL-" // type of the ammo
ITEM.description = "A box that contains %s rounds of .357 Magnum ammo. These were made in the Zone under slightly less ideal conditions.""
ITEM.longdesc = "This box is certified Match quality."
ITEM.category = "Ammunition"
ITEM.price = 1500
ITEM.flag = "A"
ITEM.ammoAmount = 15
ITEM.weight = 0.35
ITEM.isAmmo = true