ITEM.name = ".357 Magnum Match Grade"
ITEM.model = "models/ethprops/ammo/357.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.ammo = ".357 -MG-" // type of the ammo
ITEM.description = "A box that contains %s rounds of .357 Magnum ammo."
ITEM.longdesc = "This box was made to a higher standard for improved performance and a flatter trajectory."
ITEM.category = "Ammunition"
ITEM.price = 1500
ITEM.flag = "A"
ITEM.ammoAmount = 15
ITEM.weight = 0.35
ITEM.isAmmo = true