ITEM.name = "5.56x45mm Belt Zone-Loaded"
ITEM.model = "models/kek1ch/ammo_pkm.mdl"
ITEM.width = 2
ITEM.height = 1
ITEM.ammo = "5.56x45MMB -ZL-"
ITEM.description = "A belt that contains %s rounds of 5.56x45mm."
ITEM.longdesc = "These were made in the Zone under slightly less ideal conditions."
ITEM.category = "Ammunition"
ITEM.price = 6000
ITEM.flag = "A"
ITEM.ammoAmount = 200
ITEM.weight = 1.5
ITEM.isAmmo = true