ITEM.name = "7.62x54mm Belt Zone-Loaded"
ITEM.model = "models/kek1ch/ammo_pkm.mdl"
ITEM.width = 2
ITEM.height = 1
ITEM.ammo = "7.62x54MMB -ZL-"
ITEM.description = "A belt that contains %s rounds of 7.62x54mmR. These were made in the Zone under slightly less ideal conditions."
ITEM.category = "Ammunition"
ITEM.price = 11250
ITEM.flag = "A"
ITEM.ammoAmount = 100
ITEM.weight = 6
ITEM.isAmmo = true