ITEM.name = "7.62x39mm Belt Zone-Loaded"
ITEM.model = "models/silver/stalker/items/item_762x39belt.mdl"
ITEM.width = 2
ITEM.height = 2
ITEM.ammo = "7.62x39MMB -ZL-"
ITEM.description = "A belt and drum that contains %s rounds of 7.62x39mm. These were made in the Zone under slightly less ideal conditions."
ITEM.category = "Ammunition"
ITEM.price = 7500
ITEM.flag = "4"
ITEM.ammoAmount = 100
ITEM.weight = 1.7
ITEM.isAmmo = true
