ITEM.name = "7.62x39mm Belt Match Grade"
ITEM.model = "models/silver/stalker/items/item_762x39belt.mdl"
ITEM.width = 2
ITEM.height = 2
ITEM.ammo = "7.62x39MMB -MG-"
ITEM.description = "A belt and drum that contains %s rounds of 7.62x39mm. This box was made to a higher standard for improved performance and a flatter trajectory."
ITEM.category = "Ammunition"
ITEM.price = 15000
ITEM.flag = "4"
ITEM.ammoAmount = 100
ITEM.weight = 1.7
ITEM.isAmmo = true
