ITEM.name = "9x18mm Zone-Loaded"
ITEM.model = "models/kek1ch/ammo_9x18_fmj.mdl"
ITEM.ammo = "9x18MM -ZL-" // type of the ammo
ITEM.ammoAmount = 20 // amount of the ammo
ITEM.description= "A box that contains %s rounds of 9x18mm ammo."
ITEM.longdesc = "This 9x18mm round contains full metal jacket rounds with a steel penetrator and a lead core under a metal jacket. These were made in the Zone under slightly less ideal conditions."
ITEM.price = 300
ITEM.flag = "A"
ITEM.img = Material("vgui/hud/9x18.png")
ITEM.weight = 0.16
ITEM.isAmmo = true