ITEM.name = "Armoring Package"
ITEM.model = "models/kek1ch/armor_repair_pro.mdl"
ITEM.description = "A collection of armor pieces, soft kevlar and hard plate alike. Used by Duty to beef their suits up against human and mutant threats, while sacrficing environmental protection and artifact containers."
ITEM.category = "Parts"
ITEM.flag = "A"
ITEM.price = 4000
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 1