ITEM.name = "PSZ-9 Remains (Dusk)"
ITEM.model = "models/kek1ch/armor_repair_pro.mdl"
ITEM.description = "Damaged parts of a PSZ-9 vest. The armor's still usable."
ITEM.category = "Parts"
ITEM.flag = "A"
ITEM.price = 2500
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 1