ITEM.name = "3rd Gen Exoskeleton Parts (Exo)"
ITEM.model = "models/kek1ch/safe_container.mdl"
ITEM.description = "A supply crate with third generation exoskeleton servos."
ITEM.category = "Parts"
ITEM.flag = "A"
ITEM.price = 100000
ITEM.width = 2
ITEM.height = 2
ITEM.weight = 1