ITEM.name = "ASD Spare Parts (SEVA)"
ITEM.model = "models/kek1ch/armor_repair_pro.mdl"
ITEM.description = "Parts that seem to belong to a sophisticated hazmat suit."
ITEM.category = "Parts"
ITEM.flag = "A"
ITEM.price = 32000
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 1