ITEM.name = "PBF Gasmask"
ITEM.description = "A typical gasmask."
ITEM.longdesc = "A regular plastic and rubber gas mask, used for filtering air for radioactive particles and poisonous substances. It is widely used by rookies and veterans of all factions due to its universal functionality."
ITEM.model = "models/kek1ch/helm_respirator.mdl"
ITEM.price = 850
ITEM.flag = "1"
ITEM.width = 1
ITEM.height = 2
ITEM.br = 0
ITEM.fbr = 0
ITEM.ar = 0.15
ITEM.far = 1
ITEM.radProt = 0.15
ITEM.isGasmask = true
ITEM.isHelmet = true
ITEM.overlayPath = "vgui/overlays/hud_gas"
ITEM.ballisticlevels = {"0"}
ITEM.ballisticrpglevels = {["head"] = "0"}
ITEM.anomalousrpglevels = {"2","2","5","5","5"}
ITEM.img = Material("vgui/hud/eo20.png")
ITEM.ballisticRating = 10
ITEM.weight = 0.5
ITEM.res = {
	["Impact"] = 0.06,
	["Rupture"] = 0.01,
	["Bullet"] = 0.01,
	["Shock"] = 0.01,
	["Burn"] = 0.01,
	["Radiation"] = 0.19,
	["Chemical"] = 0.06,
	["Psi"] = 0.01,
}
