ITEM.name = "TIR-1 Thermal Goggles"
ITEM.description = "A pair of thermal goggles."
ITEM.longdesc = "A set of thermal goggles with a black picture that highlights IR sources. While excellent for acquiring targets in nearly all conditions, it provides very little illumination and thus can't help you find your way around the environment."
ITEM.model = "models/arctic_nvgs/nvg_t7.mdl"
ITEM.price = 35000
ITEM.flag = "4"
ITEM.height = 1
ITEM.width = 2
ITEM.br = 0.2
ITEM.fbr = 0
ITEM.ar = 0
ITEM.far = 0
ITEM.isGoggles = true
ITEM.goggleType = "nvg_t7"
ITEM.drainFactor = 2
ITEM.ballisticlevels = {"lll-a"}
ITEM.ballisticrpglevels = {["head"] = "12"}
ITEM.anomalousrpglevels = {"10","0","0","0","0"}
ITEM.weight = 5.5
