ITEM.name = "Bubble"
ITEM.model ="models/nasca/etherealsrp_artifacts/bubble.mdl"
ITEM.description = "A green artifact."
ITEM.longdesc = "A compound of several hollow, organic formations, the Bubble emits a gaseous substance that greatly neutralizes radioactive particles in an organism that breathes the emissions - without causing any additional harm. For this reason, the artifact is highly sought after and is always in demand."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 175000
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 0.7
ITEM.rads = -4