ITEM.name = "Crystal Thorn"
ITEM.model = "models/nasca/etherealsrp_artifacts/crystal_thorn.mdl"
ITEM.description = "Pointy artifact."
ITEM.longdesc = "Much like the Thorn, the Crystal Thorn is a dark orb covered in spikes. However, the effects and downsides are more pronounced, as the thorns undulate in and out of the artifact, causing larger wounds to form. For some this is a worthwhile tradeoff, as the Crystal Thorn reduced radiation by a greater amount than its smaller cousin."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 3500
ITEM.flag = "A"
ITEM.weight = 0.8
ITEM.rads = -3
ITEM.bleed = 2
