ITEM.name = "Eye"
ITEM.model ="models/nasca/etherealsrp_artifacts/eye.mdl"
ITEM.description = "This artifact looks like an eye."
ITEM.longdesc = "A rarer artifact in the shape of a glowing human eye, the Eye vastly increases the body’s metabolism, boosting the body’s ability to clot wounds considerably. The artifact incurs a larger radioactive cost, however."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 42000
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 1.1
ITEM.bleedReduce = 3
ITEM.rads = 2