ITEM.name = "Flame"
ITEM.model ="models/nasca/etherealsrp_artifacts/flame.mdl"
ITEM.description = "This artifact looks like an glassy orb."
ITEM.longdesc = "The ultimate in coagulant artifacts, the Flame is an extremely rare and powerful artifact. Beyond the power of the Mama’s Beads and the Eye, the Flame can close all but the most serious of wounds nearly instantly, but is also the most radioactive of the three. Even so, this artifact is worth a massive amount of rubles to most traders, and with good reason - it forms only in the most dangerous of thermal anomalies."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 110000
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 1.1
ITEM.bleedReduce = 4
ITEM.rads = 3