ITEM.name = "Fireball"
ITEM.model ="models/nasca/etherealsrp_artifacts/fireball.mdl"
ITEM.description = "A ball of fire. Artifact."
ITEM.longdesc = "A crystal-like artifact formed in thermal anomalies, this artifact maintains a temperature of 75 degrees Fahrenheit at all times within a small radius, seemingly regardless of surrounding factors. It does not burn the user, though it does emit radiation.\n\n+2 Radiation Protection\n-2 Thermal."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 12000
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 0.7
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.00,
	["Burn"] = -0.20,
	["Radiation"] = 0.20,
	["Chemical"] = 0.00,
	["Psi"] = 0.00,
}