ITEM.name = "Firefly"
ITEM.model ="models/nasca/etherealsrp_artifacts/firefly.mdl"
ITEM.description = "Green and beautiful artifact."
ITEM.longdesc = "Interacting with energy fields unknown to science, this artifact considerably speeds up the regeneration of tissue and organs and normalizes metabolic processes. It is rumored to be able to bring Stalkers back from the dead, though this remains unclear."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 1000000000
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 4
ITEM.passiveHeal = 45
ITEM.rads = 4