ITEM.name = "Gravi"
ITEM.model = "models/nasca/etherealsrp_artifacts/gravi.mdl"
ITEM.description = "Lumpy, reddish artifact."
ITEM.longdesc = "This artifact forms from metallic substances exposed to gravitational anomalies for prolonged periods. It has an antigravitational field around it, reducing the weight of the user's equipment by a noticeable degree.\n\nT2 Rad\n+2 Impact"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 37000
ITEM.flag = "A" 
ITEM.isArtefact = true
ITEM.weight = 0.45
ITEM.res = {
	["Fall"] = 0.20,
	["Blast"] = 0.20,
	["Bullet"] = 0.20,
	["Shock"] = 0.00,
	["Burn"] = 0.00,
	["Radiation"] = -0.20,
	["Chemical"] = 0.00,
	["Psi"] = 0.00,
}