ITEM.name = "Jellyfish"
ITEM.model = "models/nasca/etherealsrp_artifacts/jellyfish.mdl"
ITEM.description = "Cone artifact. Brown in appearance."
ITEM.longdesc = "This gravitational artifact attracts and absorbs radioactive particles, reducing the effects of radiation on the body. It is very common in the Zone and is unofficially used outside the Zone for treating acute radiation sickness in exceptional circumstances."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 2000
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 0.5
ITEM.rads = -2