ITEM.name = "Kolobok"
ITEM.model = "models/nasca/etherealsrp_artifacts/kolobok.mdl"
ITEM.description = "Very spikey artifact."
ITEM.longdesc = "A rare artifact, the Kolobok is sought across the zone for it’s above-average ability to heal wounds of all kinds that the user may incur, at the cost of being highly radioactive. Scientists have been telling stalkers that the Kolobok alters the bearer's genetic code, and those that use it often find this to be true."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 250000
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 2.1
ITEM.passiveHeal = 30
ITEM.rads = 3
