ITEM.name = "Kolobok"
ITEM.model = "models/nasca/etherealsrp_artifacts/kolobok.mdl"
ITEM.description = "Very spikey artifact."
ITEM.longdesc = "Rarely forming in anomalous areas contaminated by chemicals, this artifact is able to heal many wounds in a matter of minutes. It is rumored that this artifact interacts with the genetic code of the user, though how and what it does in this capacity is undetermined."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 250000
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 2.1
ITEM.passiveHeal = 30
ITEM.rads = 3
