ITEM.name = "Night Star"
ITEM.model ="models/nasca/etherealsrp_artifacts/nightstar.mdl"
ITEM.description = "Spikey yellow artifact. Glowing."
ITEM.longdesc = "Formed under gravitational influences, this glowing artifact generates a local, directed low-gravity field. It is commonly used to reduce the weight of equipment it is placed near.\n\nT1 Rad\n+1 Impact"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 17000
ITEM.flag = "A"
ITEM.buff = "weight"
ITEM.debuffval = 1
ITEM.isArtefact = true
ITEM.weight = 2
ITEM.res = {
	["Fall"] = 0.10,
	["Blast"] = 0.10,
	["Bullet"] = 0.10,
	["Shock"] = 0.00,
	["Burn"] = 0.00,
	["Radiation"] = -0.1,
	["Chemical"] = 0.00,
	["Psi"] = 0.00,
}