ITEM.name = "Stone Flower"
ITEM.model ="models/nasca/etherealsrp_artifacts/stoneflower.mdl"
ITEM.description = "Looks like its melted and ripped apart. Artifact."
ITEM.longdesc = "Composed of a granite-like formation deformed by gravitational forces, the metallic compounds within this artifact form a crystalline structure unexplained by science. With a beautiful luminescence, this artifact is known to have a calming effect that offers minor protection from psi-emissions.\n\nRads +1\nPsi +1"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 6400
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.00,
	["Burn"] = 0.00,
	["Radiation"] = -0.10,
	["Chemical"] = 0.00,
	["Psi"] = 0.10,
}
ITEM.weight = 1.3