ITEM.name = "Slug"
ITEM.model ="models/nasca/etherealsrp_artifacts/slug.mdl"
ITEM.description = "Very slimey."
ITEM.longdesc = "This artifact forms in chemical anomalies. It is known that using it heightens the rate of coagulation in blood, though it renders the user susceptible to various types of burns.\n\n+3 Bleed\n-2 Thermal\n-2 Chemical"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 7500
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 1.3
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.00,
	["Burn"] = -0.20,
	["Radiation"] = 0.00,
	["Chemical"] = -0.20,
	["Psi"] = 0.00,
}