ITEM.name = "Soul"
ITEM.model ="models/nasca/etherealsrp_artifacts/soul.mdl"
ITEM.description = "Spherish, blue artifact."
ITEM.longdesc = "A rare artifact seemingly formed of organic materials, it nonetheless has a striking appearance. It increases the body's overall recovery rate from any sort of damage through unknown means, but does not accelerate the accumulation of toxins."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 85000
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.passiveHeal = 15
ITEM.rads = 2
ITEM.weight = 3
