ITEM.name = "Stone Blood"
ITEM.model ="models/nasca/etherealsrp_artifacts/stoneblood.mdl"
ITEM.description = "Red and green artifact."
ITEM.longdesc = "An ugly reddish formation of compressed and polymerized plants, soil and bones, this artifact forms in gravitational anomalies. It is rather widespread and appears to partially neutralize the harmful effects of chemical poisons.\n\nRads -1 Impact\n-Decreases Stagger tier by one. Applies only to active staggers/first hits."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 7000
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.res = {
	["Fall"] = -0.10,
	["Blast"] = -0.10,
	["Bullet"] = -0.10,
	["Shock"] = 0.00,
	["Burn"] = 0.00,
	["Radiation"] = 0.00,
	["Chemical"] = 0.00,
	["Psi"] = 0.00,
}
ITEM.weight = 1.4