ITEM.name = "Thorn"
ITEM.model ="models/nasca/etherealsrp_artifacts/crystal_thorn.mdl"
ITEM.description = "Spikey artifact, but quite small."
ITEM.longdesc = "A black orb covered in long, sharp spines. Formed as the result of a Burnt Fuzz reacting with a Stalker who failed to escape its tendrils, this artifact is impossible to handle without being stabbed. However, any radionucliodes present in the bloodstream are removed in turn, making this artifact somewhat useful. Occasionally also found in other rare, organic anomalies."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 1000
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 0.3
ITEM.bleed = 1
ITEM.rads = -2
