ITEM.name = "Thorn"
ITEM.model ="models/nasca/etherealsrp_artifacts/crystal_thorn.mdl"
ITEM.description = "Spikey artifact, but quite small."
ITEM.longdesc = "Draws out radiation through the use of pricking the user’s skin, no matter if armor is worn or not. When worn will cause bleeding.\n\n+1 Chemical\n-3 Bleeding"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 2400
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 0.3
ITEM.bleed = 1
ITEM.rads = -2
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.00,
	["Burn"] = 0.00,
	["Radiation"] = 0.20,
	["Chemical"] = 0.10,
	["Psi"] = 0.00,
}