ITEM.name = "Thorn"
ITEM.model ="models/nasca/etherealsrp_artifacts/crystal_thorn.mdl"
ITEM.description = "Spikey artifact, but quite small."
ITEM.longdesc = "Draws out radiation through the use of pricking the user’s skin, no matter if armor is worn or not. When worn will cause bleeding.\n\n+1 Chemical\n-3 Bleeding"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 1000
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 0.3
ITEM.bleed = 1
ITEM.rads = -2
