ITEM.name = "Urchin"
ITEM.model ="models/nasca/etherealsrp_artifacts/urchin.mdl"
ITEM.description = "Spikey and brown artifact."
ITEM.longdesc = "Currently, the Urchin is the rarest of the Thorn family of artifacts, and easily the most potent. Reducing radiation by an extreme amount, the Urchin in turn provides the greatest blood loss. Ecologists are known to coat their suits in processed Urchins, leading to the perfected radioactive protection the SSP line of suits provides."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 24000
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 1.4
ITEM.bleed = 3
ITEM.rads = -4