ITEM.name = "Urchin"
ITEM.model ="models/nasca/etherealsrp_artifacts/urchin.mdl"
ITEM.description = "Spikey and brown artifact."
ITEM.longdesc = "Rarely forming in Burnt Fuzz anomalies, this artifact causes an increase in blood pressure along with the rapid removal of radiation contaminating the bloodstream. Scientists struggle to find a means to replicate this artifact in laboratory conditions."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 24000
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 1.4
ITEM.bleed = 3
ITEM.rads = -4