ITEM.name = "Wrenched"
ITEM.model ="models/nasca/etherealsrp_artifacts/wrenched.mdl"
ITEM.description = "Bizarre, whalelike artifact."
ITEM.longdesc = "This bizarrely-shaped artifact appears in places with increased gravitational activity. The Wrenched behaves not unlike a sponge, sucking in radioactive particles both in the environment and inside those that use it, effectively scrubbing radiation from anything near it. The Wrenched was once considered a junk artifact and exceedingly common, but recently its value has skyrocketed due to changes in its abilities as well as availability."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 39000
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 2.3
ITEM.rads = -3
