ITEM.name = "Wrenched"
ITEM.model ="models/nasca/etherealsrp_artifacts/wrenched.mdl"
ITEM.description = "Bizarre, whalelike artifact."
ITEM.longdesc = "A strangely shaped artifact resulting from gravitational anomalies, this artifact acts as a sponge absorbing radioactive particles both from the environment and the body of its user."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 39000
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 2.3
ITEM.rads = -3
