ITEM.name = "DSLR Camera"
ITEM.model = "models/maxofs2d/camera.mdl"
ITEM.description = "A working digital camera with swappable lenses, produces HD shots with varied levels of zoom. Can record video."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 2200
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 1.2