ITEM.name = "Category 2 Tier 2: Mobility Body Suit"
ITEM.description = "Ergonomic adjustments to the existing bodysuit utilizing rubber construction. Allows improved movement, even when wearing heavier or bulkier armor."
ITEM.category = "Upgrades"
ITEM.model = "models/ethprops/crafting/armor_repair_pro.mdl"
ITEM.width = 2
ITEM.height = 2
ITEM.price = 15000
ITEM.slot = 22
ITEM.isUpgrade = true
ITEM.flag = "4"
ITEM.weight = 0.75
ITEM.isArmorUpg = true
ITEM.bonusMove = 5
