ITEM.name = "Category 3 Tier 2: Synthetic Layer"
ITEM.description = "Replace cloth bits on the armor with a tougher synthetic alternative that's less susceptible to wear and tear from normal use.\n5% less armor durability damage taken"
ITEM.category = "Upgrades"
ITEM.model = "models/ethprops/crafting/armor_repair_pro.mdl"
ITEM.width = 2
ITEM.height = 2
ITEM.price = 10000
ITEM.slot = 32
ITEM.isUpgrade = true
ITEM.flag = "4"
ITEM.weight = 0.75
ITEM.isArmorUpg = true
ITEM.durabilityReduce = 0.10